version: '3.7'
services:

  electricity-php:
    build:
      ./etc/php
    container_name: electricity-php
    volumes:
      - ./:/var/www/html
    networks:
      - electricity-network

  electricity-nginx:
    image: nginx:alpine
    container_name: electricity-nginx
    restart: unless-stopped
    tty: true
    ports: [ "80:80" ]
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/:cached
    networks:
      - electricity-network

networks:
  electricity-network:
    driver: bridge
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
